version: '3.8'
services:
  gateway-service:
    image: bweera/gatewayservice
    # Add any additional configuration here
    ports:
      - "8000:8000"
    restart: always

  auth-serviceelr:
    image: bweera/authserviceelr
    # Add any additional configuration here
    ports:
      - "8070:8070"
    restart: always

  course-management-service:
    image: bweera/coursemanagementservice
    # Add any additional configuration here
    ports:
      - "4001:4001"
    restart: always

  payment-service:
    image: bweera/paymentservice
    # Add any additional configuration here
    ports:
      - "8003:8003"
    restart: always